/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tmodul5;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class frame_utama extends javax.swing.JInternalFrame {
   
    String nama ;
    int pilihan;
    String barang;
    String kode ;
    int harga;
    int total_harga;
    int beli=0;
    int bayar=0;
    int kembali;
    
    /**
     * Creates new form frame_utama
     */
    public frame_utama() {
        initComponents();
        txtjumlahbeli.setEditable(false);
        txtkembalian.setEditable(false);
        txtkodebarang.setEditable(false);
        txthargabarang.setEditable(false);
        bsimpan.setText("Simpan");
        tampil_data();
    }
     public void reset(){
        fbarang.setSelectedIndex(0);
        txtkodebarang.setText(null);
        txtnamapembeli.setText(null);
        txthargabarang.setText(null);
        txttotalharga.setText(null);
        txttotalbayar.setText(null);
        txtkembalian.setText(null);
        beli=0;
        txtjumlahbeli.setText(null);
        bsimpan.setText("Simpan");
        
        
    }
    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Barang");
        tabel.addColumn("Kode Barang");
        tabel.addColumn("Harga Barang");
        tabel.addColumn("Nama Pembeli");
        tabel.addColumn("Jumlah beli"); 
        tabel.addColumn("Total Harga");
        tabel.addColumn("Total Bayar");
        tabel.addColumn("Kembalian");
        
        try{
            java.sql.Connection conn = tmodul5.Tmodul5.koneksiDB();
            String query="select* from tb_penjualan";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                Object[]row ={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
                tabel.addRow(row);
            }
             data.setModel(tabel);
             data2.setModel(tabel);
       
        }catch(Exception e){
        e.printStackTrace();
    }
    }
    
    public void tampil_data_awal() {
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("Nama Barang");
    tabel.addColumn("Kode Barang");
    tabel.addColumn("Harga Barang");
    tabel.addColumn("Nama Pembeli");
    tabel.addColumn("Jumlah beli");
    tabel.addColumn("Total Harga");
    tabel.addColumn("Total Bayar");
    tabel.addColumn("Kembalian");

    try {
        java.sql.Connection conn = tmodul5.Tmodul5.koneksiDB();
        String query = "SELECT * FROM tb_penjualan"; 
        java.sql.PreparedStatement pst = conn.prepareStatement(query);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            Object[] row = { rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),
                             rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8) };
            tabel.addRow(row);
        }

        // Mengosongkan data yang sudah ada sebelumnya
        data.setModel(new DefaultTableModel());
        data.setModel(tabel);
        
        // Menetapkan model tabel ke data2
        data2.setModel(new DefaultTableModel());
        data2.setModel(tabel);

    } catch (Exception e) {
        e.printStackTrace();
    }
}

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalSeluruhPenjualan = new javax.swing.JTextField();
        btnTotalSeluruhPenjualan = new javax.swing.JButton();
        btnRiset2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txthargabarang = new javax.swing.JTextField();
        txtnamapembeli = new javax.swing.JTextField();
        txtjumlahbeli = new javax.swing.JTextField();
        txttotalharga = new javax.swing.JTextField();
        txtkodebarang = new javax.swing.JTextField();
        txttotalbayar = new javax.swing.JTextField();
        txtkembalian = new javax.swing.JTextField();
        fbarang = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        btambah = new javax.swing.JButton();
        bkurang = new javax.swing.JButton();
        bbayar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bbersih = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        breset = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        data2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Kode", "Harga", "Pembeli", "Jumlah Beli", "Total ", "Jumlah Bayar", "Kembali"
            }
        ));
        jScrollPane1.setViewportView(data2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Informasi Total Penjualan");

        jLabel2.setText("Total Penjualan");

        btnTotalSeluruhPenjualan.setBackground(new java.awt.Color(255, 204, 153));
        btnTotalSeluruhPenjualan.setText("Total");
        btnTotalSeluruhPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalSeluruhPenjualanActionPerformed(evt);
            }
        });

        btnRiset2.setBackground(new java.awt.Color(255, 204, 153));
        btnRiset2.setText("Riset");
        btnRiset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTotalSeluruhPenjualan)
                                .addGap(34, 34, 34)
                                .addComponent(btnRiset2)
                                .addGap(230, 230, 230)
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(txtTotalSeluruhPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalSeluruhPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnTotalSeluruhPenjualan)
                    .addComponent(btnRiset2))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Laporan", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Transaksi Penjualan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jLabel5.setText("Nama Barang");

        jLabel6.setText("Kode Barang");

        jLabel7.setText("Harga Barang");

        jLabel8.setText("Nama Pembeli");

        jLabel9.setText("Jumlah Beli");

        jLabel10.setText("Total Harga");

        jLabel11.setText("Total Bayar");

        jLabel12.setText("Kembalian");

        txthargabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargabarangActionPerformed(evt);
            }
        });

        txtnamapembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapembeliActionPerformed(evt);
            }
        });

        txtkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebarangActionPerformed(evt);
            }
        });

        txttotalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalbayarActionPerformed(evt);
            }
        });

        fbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Bola Voli", "Bola Basket ", "Barbel", "Raket Badminton ", "Kacamata Renang", "Raket Tenis", "Matras", "Sepatu Roda", "Sepeda Statis", "Bola Kasti", " " }));
        fbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbarangActionPerformed(evt);
            }
        });

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Kode", "Harga", "Nama Pembeli", "Jumlah Beli", "Total Harga", "Total Bayar", "Kembalian"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(data);

        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        bkurang.setText("-");
        bkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkurangActionPerformed(evt);
            }
        });

        bbayar.setBackground(new java.awt.Color(255, 255, 204));
        bbayar.setText("Bayar");
        bbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbayarActionPerformed(evt);
            }
        });

        bbersih.setBackground(new java.awt.Color(255, 255, 204));
        bbersih.setText("Bersih");
        bbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        breset.setText("Reset");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });

        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtkodebarang)
                                .addComponent(txthargabarang)
                                .addComponent(fbarang, 0, 124, Short.MAX_VALUE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(54, 54, 54)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txttotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(bbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnamapembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fbarang)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txttotalbayar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtkembalian))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bkurang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtjumlahbeli)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbersih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Penjualan", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthargabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargabarangActionPerformed

    private void txtnamapembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapembeliActionPerformed
        nama = txtnamapembeli.getText();
    }//GEN-LAST:event_txtnamapembeliActionPerformed

    private void txttotalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalbayarActionPerformed
        bayar = Integer.parseInt(txttotalbayar.getText());
    }//GEN-LAST:event_txttotalbayarActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
         if (bsimpan.getText().equals("Simpan")) {
        if (barang==null||kode==null||harga==0||beli==0||total_harga==0||bayar==0) {
            JOptionPane.showMessageDialog(null, "Tolong Input Data dengan Benar");
              reset();
        }else{
        try{
            String sql="insert into tb_penjualan values('"+barang+"','"+kode+"','"+harga+"','"+txtnamapembeli.getText()+"','"+beli+"','"+total_harga+"','"+bayar+"','"+kembali+  "')";
            java.sql.Connection conn=(java.sql.Connection)tmodul5.Tmodul5.koneksiDB();
            java.sql.PreparedStatement 
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            reset();
            tampil_data();

        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
        }
         }else if (bsimpan.getText().equals("Edit")){
             try{
            String update ="UPDATE tb_penjualan SET harga_barang='"+harga+"',kode_barang='"+kode+"',nama_barang='"+barang+"',jumlah_beli='"+beli+"',total_harga='"+total_harga+"',total_bayar='"+bayar+"',kembalian='"+kembali+"' where nama_pembeli='"+txtnamapembeli.getText()+"'";
            java.sql.Connection conn=(java.sql.Connection)tmodul5.Tmodul5.koneksiDB();
            java.sql.PreparedStatement 
            pst=conn.prepareStatement(update);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Edit Berhasil disimpan");
            reset();
            tampil_data();
     
             }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
      }
        
    }//GEN-LAST:event_bsimpanActionPerformed

    private void fbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbarangActionPerformed
        pilihan = fbarang.getSelectedIndex();
        if(pilihan==0){
            reset();
        }

        if(pilihan==1){
            kode = "001";
            harga = 600000;
            barang = "Bola Voli";
        } 
        if(pilihan==2){
            kode = "002";
            harga = 450000;
            barang = " Bola Baket";
        }
        if(pilihan==3){
            kode = "003";
            harga = 250000;
            barang = " Barbel";
        }
        if(pilihan==4){
            kode = "004";
            harga = 500000;
            barang = "Raket Badminton";
        }
        if(pilihan==5){
            kode = "005";
            harga = 100000;
            barang = " Kacamata Renang";
        }
        if(pilihan==6){
            kode = "006";
            harga = 320000;
            barang = " Raket Tenis";
        }
        if(pilihan==7){
            kode = "007";
            harga = 200000;
            barang = " Matras";
        }
        if(pilihan==8){
            kode = "008";
            harga = 300000;
            barang = " Sepatu Roda";
        }
        if(pilihan==9){
            kode = "009";
            harga = 1000000;
            barang = " Sepeda Statis";
        }
        if(pilihan==10){
            kode = "010";
            harga = 150000;
            barang = " bola kasti";
        }
        txtkodebarang.setText(kode);
        txthargabarang.setText(""+harga);

    }//GEN-LAST:event_fbarangActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
         if(data==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
         }else if(txtkodebarang.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus!");
        } else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan dihapus?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
               try{
               String sql="delete from tb_penjualan where nama_pembeli ='"+ nama+"'";
               java.sql.Connection conn=(java.sql.Connection)tmodul5.Tmodul5.koneksiDB();
               java.sql.PreparedStatement 
               pst=conn.prepareStatement(sql);
               pst.execute();
               JOptionPane.showMessageDialog(null, "Berhasil dihapus");
               tampil_data();
               reset();
               
               }
            catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
            } 
            }
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        if(data==null){
            JOptionPane.showMessageDialog(null, "Data Telah kosong!");
        }else{
            int jawab = JOptionPane.showConfirmDialog(null,"Apakah Yakin Data akan direset?","Konfirmasi",JOptionPane.YES_NO_OPTION);
            if(jawab==0){
                try{
                    String sql="delete from tb_penjualan ";
                    java.sql.Connection conn=(java.sql.Connection)tmodul5.Tmodul5.koneksiDB();
                    java.sql.PreparedStatement
                    pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Berhasil disimpan");
                    reset();
                    tampil_data();
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal disimpan");
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_bresetActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
     
            int baris = data.rowAtPoint(evt.getPoint());

            String a = data.getValueAt(baris, 0).toString();
            fbarang.setSelectedItem(a);
            String b = data.getValueAt(baris, 1).toString();
            txtkodebarang.setText(b);
            String c = data.getValueAt(baris, 2).toString();
            txthargabarang.setText(c);
            String d = data.getValueAt(baris, 3).toString();
            txtnamapembeli.setText(d);
            nama = d; // Perbarui nilai nama pembeli
            String e = data.getValueAt(baris, 4).toString();
            txtjumlahbeli.setText(e);
            String f = data.getValueAt(baris, 5).toString();
            txttotalharga.setText(f);
            String g = data.getValueAt(baris, 6).toString();
            txttotalbayar.setText(g);
            String h = data.getValueAt(baris, 7).toString();
            txtkembalian.setText(h);
            bsimpan.setText("Edit");

    }//GEN-LAST:event_dataMouseClicked

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        beli++;
        txtjumlahbeli.setText(Integer.toString(beli));
        total_harga = beli*harga;
        txttotalharga.setText(""+total_harga);
    }//GEN-LAST:event_btambahActionPerformed

    private void bkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkurangActionPerformed
        beli--;
        txtjumlahbeli.setText(Integer.toString(beli));
        if (beli<0){
            txtjumlahbeli.setText("0");
            beli=0;
        }
        txtjumlahbeli.setText(Integer.toString(beli));
        total_harga = beli*harga;
        txttotalharga.setText(""+total_harga);
    }//GEN-LAST:event_bkurangActionPerformed

    private void bbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbayarActionPerformed
        nama=txtnamapembeli.getText();
        String totalBayarText = txttotalbayar.getText().trim(); // Dapatkan teks dan hapus spasi
        if (totalBayarText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan pembayaran dengan benar. Harap isi total bayar.");
        }else{
            bayar = Integer.parseInt(totalBayarText);
            //         bayar = Integer.parseInt(txttotalbayar.getText());
            if(bayar==0||bayar<total_harga){
                //         bayar = Integer.parseInt(txttotalbayar.getText());
                JOptionPane.showMessageDialog(null, "Pembayaran anda kurang, Tolong Masukan Pembayaran dengan sesuai!!");
            }else{
                //         bayar = Integer.parseInt(txttotalbayar.getText());
                kembali = bayar-total_harga;
                txtkembalian.setText(""+kembali);
            }
        }
    }//GEN-LAST:event_bbayarActionPerformed

    private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
        if(txtkodebarang.getText().equals("")&&txtnamapembeli.getText().equals("")&&txttotalharga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Form Input Sudah bersih");
        }else {
            reset();
        }
    }//GEN-LAST:event_bbersihActionPerformed

    private void btnTotalSeluruhPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalSeluruhPenjualanActionPerformed
        // TODO add your handling code here:
     int totalKeseluruhan = 0;

    for (int i = 0; i < data.getRowCount(); i++) {
        int totalHarga = Integer.parseInt(data.getValueAt(i, 5).toString());
        totalKeseluruhan += totalHarga;
    }

    // Menampilkan total keseluruhan pada textfieldTotalHargaPenjualan
    txtTotalSeluruhPenjualan.setText(String.valueOf(totalKeseluruhan));
    }//GEN-LAST:event_btnTotalSeluruhPenjualanActionPerformed

    private void txtkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebarangActionPerformed

    private void btnRiset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiset2ActionPerformed
        // TODO add your handling code here:
        txtTotalSeluruhPenjualan.setText("");
    }//GEN-LAST:event_btnRiset2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbayar;
    private javax.swing.JButton bbersih;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkurang;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JButton btnRiset2;
    private javax.swing.JButton btnTotalSeluruhPenjualan;
    private javax.swing.JTable data;
    private javax.swing.JTable data2;
    private javax.swing.JComboBox<String> fbarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtTotalSeluruhPenjualan;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtkodebarang;
    private javax.swing.JTextField txtnamapembeli;
    private javax.swing.JTextField txttotalbayar;
    private javax.swing.JTextField txttotalharga;
    // End of variables declaration//GEN-END:variables
}